### ISSUE TITLE
Support for multiple accounts

### ISSUE THREAD

**Issue by felixge** [nodejitsu/node-cloudfiles#2] opened 2010-10-23 13:56 UTC
Just looked over the code, and it seems like setAuth effects the state of the module, making it impossible to work with multiple accounts. Is that correct, or are there no race conditions to be expected when calling `setAuth`?

**Comment by indexzero** [comment] 2010-10-23 17:04
No, this was a by design decision that I made. I've been rethinking it though as we've had some multi-account needs at Nodejitsu. Perhaps refactoring 'core.js' into 'client.js' to support these scenarios. 

There would probably be race conditions from this line, since the X-AUTH-TOKEN is set from the cloudfiles.config object: http://github.com/nodejitsu/node-cloudfiles/blob/master/lib/cloudfiles/utils.js#L120

**Comment by indexzero** [comment] 2010-12-25 18:52
Fixed in 0.2.0

**Closed as completed by indexzero** 2010-12-25 18:52 UTC
